from src.models.prompts.nfse_prompts import (
    PROMPT_EXTRACT_NFSE_GEMMA,
    PROMPT_INCOMPLETE_RESPONSE,
    PROMPT_INVALIDOS_RESPONSE,
    PROMPT_NO_DATA_RESPONSE,
)
from src.models.prompts.onboard_prompts import (
    PROMPT_CONSULTA,
    PROMPT_REF_PAST,
    PROMPT_HISTORY_RESPONSE,
)

from src.models.prompts.conversation_prompts import (
    PROMPT_HAS_INTENT,
    PROMPT_NO_INTENT_RESPONSE,
    PROMPT_CLASSIFICA_INTENT,
    PROMPT_PARECE_PERGUNTA,
)

from src.models.prompts.prestador_prompts import (
    PROMPT_EXTRACT_PREST_DATA,
    PROMPT_INCOMPLETE_PREST_DATA_RESPONSE,
    PROMPT_INVALIDOS_PREST_RESPONSE,
    PROMPT_NO_DATA_PREST_RESPONSE,
    PROMTP_EXTRACT_ADDRESS,
    PROMPT_CLASSIFICA_INTENT_PREST,
    PROMPT_GENERAL_ASK,
    PROMPT_NO_INTENT_PREST,
)

__all__ = [
    "PROMPT_EXTRACT_NFSE_GEMMA",
    "PROMPT_EXTRACT_NFSE_CLAUDE",
    "TOOL_EXTRACT_NFSE",
    "PROMPT_PRESTADOR_CADASTRO",
    "PROMPT_ENDERECO_GEMMA",
    "PROMPT_CONSULTA",
    "PROMPT_CLASSIFICA_INTENT",
    "PROMPT_NO_INTENT_RESPONSE",
    "PROMPT_HAS_INTENT",
    "PROMPT_PARECE_PERGUNTA",
    "PROMPT_REF_PAST",
    "PROMPT_HISTORY_RESPONSE",
    "PROMPT_INCOMPLETE_RESPONSE",
    "PROMPT_INVALIDOS_RESPONSE",
    "PROMPT_NO_DATA_RESPONSE",
    "PROMPT_EXTRACT_PREST_DATA",
    "PROMPT_INCOMPLETE_PREST_DATA_RESPONSE",
    "PROMPT_INVALIDOS_PREST_RESPONSE",
    "PROMPT_NO_DATA_PREST_RESPONSE",
    "PROMTP_EXTRACT_ADDRESS",
    "PROMPT_CLASSIFICA_INTENT_PREST",
    "PROMPT_GENERAL_ASK",
    "PROMPT_NO_INTENT_PREST",
]